# Generated by Django 6.0.3 on 2026-03-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_shop_admin_notes_shop_expires_at_shop_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='whatsapp_number',
        ),
        migrations.AddField(
            model_name='shop',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
