# Generated by Django 6.0.3 on 2026-04-06 06:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_recreate_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('flag', 'Product Flagged'), ('unflag', 'Product Unflagged'), ('warn', 'Shop Warned'), ('suspend_temp', 'Shop Suspended (Temp)'), ('ban', 'Shop Permanently Banned'), ('restore', 'Shop Restored')], max_length=20)),
                ('target_label', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('admin_label', models.CharField(default='admin', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('is_data_deletion_request', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='shop',
            name='custom_domain',
            field=models.CharField(blank=True, max_length=253, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('premium', 'Premium')], default='starter', max_length=20),
        ),
        migrations.AddField(
            model_name='shop',
            name='suspension_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='suspension_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='suspension_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_logs', to='accounts.shop'),
        ),
        migrations.AddField(
            model_name='staffaccount',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_accounts', to='accounts.shop'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='accounts.shop'),
        ),
    ]
