# Generated by Django 6.0.3 on 2026-05-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_cleanup_unused_plan_suspension_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSettings',
        ),
        migrations.AddField(
            model_name='shop',
            name='is_pro',
            field=models.BooleanField(default=False),
        ),
    ]
