# Generated by Django 6.0.3 on 2026-04-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flag_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
