# Generated by Django 6.0.3 on 2026-07-17 08:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0013_delete_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProAboutBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_about_blocks', to='accounts.shop')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProContactInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_line1', models.CharField(blank=True, default='', max_length=255)),
                ('address_line2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('whatsapp_override', models.CharField(blank=True, default='', help_text='Override WhatsApp number. If blank, falls back to shop phone.', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('hours_mon', models.CharField(blank=True, default='', max_length=30)),
                ('hours_tue', models.CharField(blank=True, default='', max_length=30)),
                ('hours_wed', models.CharField(blank=True, default='', max_length=30)),
                ('hours_thu', models.CharField(blank=True, default='', max_length=30)),
                ('hours_fri', models.CharField(blank=True, default='', max_length=30)),
                ('hours_sat', models.CharField(blank=True, default='', max_length=30)),
                ('hours_sun', models.CharField(blank=True, default='Closed', max_length=30)),
                ('google_maps_embed_url', models.URLField(blank=True, default='', max_length=1000)),
                ('instagram_url', models.URLField(blank=True, default='', max_length=300)),
                ('facebook_url', models.URLField(blank=True, default='', max_length=300)),
                ('youtube_url', models.URLField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pro_contact_info', to='accounts.shop')),
            ],
        ),
    ]
