# Generated by Django 6.0.3 on 2026-07-26 15:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_delete_sitesettings'),
        ('pro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProHeroSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hero_image_url', models.URLField(blank=True, default='', max_length=500)),
                ('hero_headline', models.CharField(blank=True, default='', max_length=200)),
                ('hero_subheading', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pro_hero_settings', to='accounts.shop')),
            ],
        ),
    ]
